//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneNETDataReceiver.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IoTWebEntities : DbContext
    {
        public IoTWebEntities()
            : base("name=IoTWebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<DeviceValue> DeviceValue { get; set; }
        public virtual DbSet<HistoryValue> HistoryValue { get; set; }
        public virtual DbSet<HistoryValueServerSide> HistoryValueServerSide { get; set; }
        public virtual DbSet<OneNetProduct> OneNetProduct { get; set; }
        public virtual DbSet<Renjianxin_ButtonClick> Renjianxin_ButtonClick { get; set; }
        public virtual DbSet<Renjianxin_HealthData> Renjianxin_HealthData { get; set; }
        public virtual DbSet<SMSDeviceInfo> SMSDeviceInfo { get; set; }
        public virtual DbSet<SysLog> SysLog { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
    }
}
